Options for mesh adapt
SCOREC/core pull request #342
Opened 2021-06-29 20:37 UTC by mortezah

This pull request includes a couple of logic for setting mesh adapt options. In particular,

1. logic to compute `in->maximumIterations` based on the requested size field and current mesh size.
2. logic to invoke Pre, Post, or Mid balancer if the mesh imbalance becomes larger than `in->maximumImbalance` during mesh adapt.

2021-06-30 00:08 UTC, mortezah commented
@cwsmith I have added this condition https://github.com/mortezah/core/blob/f9005bb6c0f158a5b66c38953d4bd4318f01a320/ma/maInput.cc#L139 to prevent setting more than one of these flags `in->shouldRunPreZoltan`, `in->shouldRunPreZoltan`, and `in->shouldRunPreParma` to true at the same time. However, it seems that some of the tests (for example `refine2x.cc` here https://github.com/SCOREC/core/blob/f5025752630b03dff41251cad1ac829d8c275a3f/test/refine2x.cc#L107) turns on both `PreZoltanRib` and `PreParma`. Any idea why both options are turned on in `refine2x`?

2021-06-30 13:10 UTC, cwsmith requested changes
Looks good.  I submitted a PR to your branch for a small cmake change.

2021-06-30 14:02 UTC, mortezah commented on CMakeLists.txt
> +  add_definitions(-DHAVE_ZOLTAN)
@cwsmith thanks. I pull those chagnes.

2021-06-30 17:36 UTC, mortezah commented on ma/maBalance.cc
> +    if (PCU_Comm_Peers() < 16000) {
@cwsmith I have added `MAX_ZOLTAN_GRAPH_RANK`. I have also updated the documentation in `maInput.h` for oxygen to reflect the behavior of mesh adapt based on these changes.

2021-07-01 15:30 UTC, cwsmith approved these changes

2021-07-01 15:32 UTC, merged