Add nompi stub
SCOREC/core pull request #425
Opened 2024-04-26 22:44 UTC by bobpaw

## Add nompi stub

Add a stub implementation of MPI in `pcu/pcu_pnompi.c`.
Remove direct calls to MPI functions.

This adds a `SCOREC_NO_MPI` build option for users running on single-process, single-machine setups that do not want to compile with MPI. Message passing is simulated in memory.

2024-04-26 22:55 UTC, bobpaw commented
@cwsmith, build is failing for this PR. I think we should add `PCU_Init` and `PCU_Finalize` facades that wrap the MPI calls and do a `PCU_Comm_Init()` and `PCU_Comm_Free()` to remove the direct dependencies. There are a lot of executables that would need to be changed and this would become a large PR. Alternatively, we could define a replacement `MPI_Init` and `MPI_Finalize` in pcu_pnompi and link to those. Or, we could do a hybrid approach and encourage people to use `PCU_Init` in the future.

2024-04-29 03:10 UTC, jacobmerson commented
@flagdanger and I are working on a very large update of PCU that should make this all easier by getting rid of the singleton. Pull request for that coming within the next week.

2024-04-29 14:30 UTC, jacobmerson commented
@bobpaw sorting out a few things to make the pull request ready to merge, but #388 the draft pull request for replacing the singleton in PCU.

Although we replaced the interface used in the test cases, this pull request is designed to work with no modification to existing codes by using a global PCU state when the old style interface is used with `PCU_Comm_Init` or it can use local state.

2024-04-30 16:54 UTC, bobpaw commented
@jacobmerson, we will plan to use your PR for the future of core, but the sponsor wants this functionality soon, so we will use this branch until yours is finished.

2024-04-30 16:58 UTC, cwsmith commented
@bobpaw Does `PCU_Comm_Init()` check if MPI was initialized?

2025-02-06 15:30 UTC, bobpaw commented
@cwsmith, after seeing the new PCU object introduced by #433, we would still like to take this build-time stubbing approach. This PR results in compilation of the entire repository without MPI dependence. Since I merged develop a few times, should we squash this PR?

2025-02-06 15:54 UTC, cwsmith requested changes
LGTM.  Thank you.  There are a few comments below.

2025-02-06 15:54 UTC, cwsmith commented on CMakeLists.txt
> +option(SCOREC_NO_MPI "Use a stub MPI implementation" OFF)
```suggestion
option(SCOREC_NO_MPI "Disable MPI support.  When enabled only serial execution is supported." OFF)
```

2025-02-06 15:54 UTC, cwsmith commented on pcu/PCU.h
> +extern "C"
What is the scope of these macros?  We still want to let users of PUMI run their application in parallel even if PUMI is only built for serial execution.

I think we should add a test that builds an MPI hello world app and links against a 'SCOREC_NO_MPI=on' build, and loads a serial pumi mesh etc..  This will help ensure that the symbols don't leak in the long run.

2025-02-06 15:54 UTC, cwsmith commented on pcu/PCU_C.h
> +extern "C"
same scope question as in PCU.h

2025-02-06 15:54 UTC, cwsmith commented on pcu/pcu_pnompi_types.h
> +#define MPI_INT 2
same scope question as in PCU.h

2025-02-06 15:54 UTC, cwsmith commented on test/pumi.cc
> -#include <mpi.h>
If SCOREC_NO_MPI=ON, then unless the user is compiling with the mpi wrappers, then source code and tests cannot `#include <mpi.h>`.  Is that correct?  If so, we should document that in the users and developers guide and that no MPI functions should be called directly within PUMI source.

2025-02-06 15:54 UTC, cwsmith commented on test/testing.cmake
> +  if(${PROCS} EQUAL "1")
```suggestion
if(SCOREC_NO_MPI AND ${PROCS} EQUAL "1")
```
Will that work?

2025-02-06 15:54 UTC, cwsmith commented on test/smokeTesting.cmake
> +  if(PROCS EQUAL "1")
```suggestion
if(SCOREC_NO_MPI AND ${PROCS} EQUAL "1")
```
Will that work?

2025-02-06 17:39 UTC, bobpaw commented on test/testing.cmake
> +  if(${PROCS} EQUAL "1")
No, and I updated the indentation to make it clearer what's going on. If SCOREC_NO_MPI is given, I want to only add serial tests. If AND is used instead, then parallel tests will still be added as usual.

2025-02-06 17:46 UTC, bobpaw commented on pcu/PCU.h
> +extern "C"
This is a really good point. Right now, those macros would spread to every source that includes PCU.h. I think a simple `#ifndef MPI_COMM_WORLD` may suffice in these cases. Then PUMI tests will use the stub MPI_Init and end-users can `#include <mpi.h>` before PCU.h and they will get the real versions.

I will work on making a test case so that we can observe the negative first before trying that fix.

Also, it would require a major notice to end-users (since include order is not usually important). What do you think?

2025-02-06 17:55 UTC, cwsmith commented on pcu/PCU.h
> +extern "C"
If building with SCOREC_NO_MPI=off then I assume that everything that worked prior to this PR would continue to work.  Is that correct?  If so, then I think we could count this as a new 'feature' with specific requirements (i.e., include order, no mpi headers, etc.).

2025-02-06 18:16 UTC, bobpaw commented on pcu/PCU.h
> +extern "C"
Also, I see the Developer Guide on the Wiki which I will update after merging this PR. Is the user guide LaTeX anywhere? A quick Ctrl+F doesn't show any reference to any of the `SCOREC_*` build options.

2025-02-06 18:20 UTC, cwsmith commented on pcu/PCU.h
> +extern "C"
> Should this be a GitHub action, similar to building the doc/ folder?

Yes.

> latex 

The latex files for the user guide are here:

https://github.com/SCOREC/pumi-docs/tree/master/userGuide

2025-02-06 22:58 UTC, bobpaw commented
Before I make my example project I have a feeling I will need to add a config file, called something like `mpi_rpc.h` (@cwsmith I would appreciate input on the name) which will be generated to make SCOREC_NO_MPI persistent. Then I can bundle the PCU.h `#ifdef SCOREC_NO_MPI` logic and the content in pcu_pnompi_types.h into one file.

2025-02-07 18:11 UTC, cwsmith commented
We should probably just make a PUMI_config.h file ([like this](https://github.com/SCOREC/meshFields/blob/main/src/MeshField_Config.hpp.in)) and the first entry in it can be the `SCOREC_NO_MPI` flag.  Over time, we can move away from using `add_definition(...)` to the config file approach.

2025-02-20 04:18 UTC, bobpaw commented on pcu/PCU_C.h
> +extern "C"
Removed these macros and added `#ifndef SCOREC_NO_MPI` to all test cases. Additionally, the change is less obscure to someone casually reading tests as examples.

2025-02-20 04:43 UTC, jacobmerson requested changes
I mostly focused on the changes in the C++ and CMake code and did not review the C implementation in detail.

I have one major concern that we need to clarify before merging is a more concrete understanding of the semantics of the class's comm ownership. I'm currently against a shared ownership model for this particular case. And, highly against anything that puts the onus of remembering to clean things up on the user. Is there a simple case that can demonstrate why you needed to add the `ownscomm` logic?

The other more minor concern is that we should get rid of the need for #ifdefs in the user code by providing our own `init` and `finalize` routines. That will substantially clean up the executables.

The rest is very minor stuff that should be quick to update.

Otherwise, I think this is very much moving in the right direction. The changes clean up a fair number of places where we have a mix of MPI and PCU use which is bound to cause issues.

2025-02-20 04:43 UTC, jacobmerson commented on phasta/CMakeLists.txt
> -    $<INSTALL_INTERFACE:include>
why is `include` not needed?

2025-02-20 04:43 UTC, jacobmerson commented on pcu/PCU.cc
> +PCU(MPI_COMM_WORLD)
You should never actually use `MPI_COMM_WORLD`, instead call `MPI_Comm_dup` on the world communicator.

2025-02-20 04:43 UTC, jacobmerson commented on pcu/pcu_pmpi.c
> +  MPI_Comm_compare(self->original_comm, MPI_COMM_WORLD, &result);
if you use `MPI_Comm_dup` above instead of directly using `MPI_COMM_WORLD` you will not need this.

2025-02-20 04:43 UTC, jacobmerson commented on phasta/adaptLvlSet_loop.cc
> +#endif
Is there a way we can get rid of the `#ifdef` from all the user code? One potentially bad idea: 
define a `PCU_Initialize` and `PCU_finalize` functions and put this code inside those. Until we have proper MPI sessions support, I'm not sure if there is much better that we can do.

2025-02-20 04:43 UTC, jacobmerson commented on pumi/CMakeLists.txt
> -    $<INSTALL_INTERFACE:include>
why is `include` not needed?

2025-02-20 04:43 UTC, jacobmerson commented on pumi/pumi_mesh.cc
> +  m->getPCU()->Add(global_own_entity_count, 4);
I think this needs a comment describing what's going on here. Should there be a `PCU_Allreduce`?

2025-02-20 04:43 UTC, jacobmerson commented on python_wrappers/CMakeLists.txt
> -    $<INSTALL_INTERFACE:include>
why is include path removed?

2025-02-20 04:43 UTC, jacobmerson commented on ree/CMakeLists.txt
> -    $<INSTALL_INTERFACE:include>
why is include path removed?

2025-02-20 04:43 UTC, jacobmerson commented on sam/CMakeLists.txt
> -    $<INSTALL_INTERFACE:include>
why is include path removed?

2025-02-20 04:43 UTC, jacobmerson commented on spr/CMakeLists.txt
> -    $<INSTALL_INTERFACE:include>
why is include path removed?

2025-02-20 04:43 UTC, jacobmerson commented on stk/CMakeLists.txt
> -    $<INSTALL_INTERFACE:include>
why is include path removed?

2025-02-20 04:43 UTC, jacobmerson commented on zoltan/CMakeLists.txt
> -    $<INSTALL_INTERFACE:include>
why is include path removed?

2025-02-20 04:43 UTC, jacobmerson commented on pcu/PCU.cc
> +PCU_Comm PCU::GetComm() const noexcept { return mpi_->original_comm; }
I'm wondering if we should remove this from the interface. Otherwise, it may be too tempting to drop out of `PCU` to `MPI` which will break the no mpi use case.

2025-02-20 15:11 UTC, bobpaw commented on pcu/PCU.cc
> +PCU_Comm PCU::GetComm() const noexcept { return mpi_->original_comm; }
I think there are cases where users may want access to advanced MPI features. A simple one I can think of (I have limited MPI experience) is if a user wants to call MPI_Comm_compare.

2025-02-20 15:22 UTC, bobpaw commented on example/mpi-nompi/hello.cc
> +  pcu::PCU *PCUObj = new pcu::PCU(MPI_COMM_WORLD);
I don't like how we have to introduce a scope just to destruct the PCUObj at a certain time. I use new and delete to explicitly destroy it before MPI_Finalize.

2025-02-20 15:32 UTC, bobpaw commented on example/mpi-nompi/hello.cc
> +  int *vals1 = new int[size];
Raw new is not really bad in a test like this because I know I am two lines later but I have changed it to std::vector

2025-02-20 15:33 UTC, bobpaw commented on gmi/CMakeLists.txt
> -    $<INSTALL_INTERFACE:include>
See above comment, let's discuss there.

2025-02-20 15:34 UTC, bobpaw commented on example/mpi-nompi/hello.cc
The mpi-nompi example is an MPI application linked to SCOREC compiled with SCOREC_NO_MPI. It demonstrates and tests the combination of the two.

2025-02-20 15:34 UTC, bobpaw commented on gmi_cap/CMakeLists.txt
> -    $<INSTALL_INTERFACE:include>
See above comment, let's discuss there.

2025-02-20 15:34 UTC, bobpaw commented on gmi_sim/CMakeLists.txt
> -    $<INSTALL_INTERFACE:include>
See above comment, let's discuss there.

2025-02-20 15:35 UTC, bobpaw commented on mds/CMakeLists.txt
> -    $<INSTALL_INTERFACE:include>
See above comment, let's discuss there.

2025-02-20 15:37 UTC, bobpaw commented on pcu/PCU.cc
> +double Time() noexcept {
I like that idea. In our stub we looked at the OpenMPI implementation (I think, but maybe mpich) to decide what to put. If I had to guess, they resorted to gettimeofday/other functions to ensure compatibility. But since C++ has standard clocks we don't have to screw around trying to be compatible.

2025-02-20 15:42 UTC, bobpaw commented on pcu/PCU.cc
> +bool PCU::OwnsComm() const noexcept { return mpi_->owned; }
`GetMPIComm` and `GetComm` are marked `[[nodiscard]]`:

https://github.com/SCOREC/core/blob/b0f5bf12e76968623e4eb637509130a3b6595db7/pcu/PCU.h#L34

Do you mean `OwnsComm(void)`? Do you want to differentiate it from `OwnsComm(bool)`?

2025-02-20 15:49 UTC, bobpaw commented on pcu/PCU.cc
> +PCU_Comm PCU::SwitchMPIComm(PCU_Comm newcomm) noexcept {
Done

2025-02-20 15:49 UTC, bobpaw commented on pcu/PCU.cc
> +PCU_Comm PCU::SwitchComm(PCU_Comm newcomm) noexcept {
Did this already and it must be in the header not the source.

2025-02-20 15:50 UTC, bobpaw commented on pcu/PCU.cc
> +  template T PCU::Exscan<T>(T p) noexcept;                                     \
These are explicit template instantiations, not the declaration, so not the right place for the attribute.

2025-02-20 15:51 UTC, bobpaw commented on sam/CMakeLists.txt
> -    $<INSTALL_INTERFACE:include>
See above comment, let's discuss there.

2025-02-20 15:51 UTC, bobpaw commented on spr/CMakeLists.txt
> -    $<INSTALL_INTERFACE:include>
See above comment, let's discuss there.

2025-02-20 15:51 UTC, bobpaw commented on zoltan/CMakeLists.txt
> -    $<INSTALL_INTERFACE:include>
See above comment, let's discuss there.

2025-02-20 15:52 UTC, bobpaw commented on stk/CMakeLists.txt
> -    $<INSTALL_INTERFACE:include>
See above comment, let's discuss there.

2025-02-20 15:59 UTC, bobpaw commented on pcu/PCU.h
> +  bool OwnsComm() const noexcept;
When `PCU::Split()` is used, a new communicator is constructed with the newcomm from MPI_Comm_split. This MPI communicator needs to be freed. Before this PR, PCU only manages `user_comm` and `coll_comm`. The `original_comm` passed to the constructor is copied and not touched during destruction (`pcu_pmpi_finalize`). We considered using something like `PCU::FreeComm` to destroy the underlying split communicator, but then the dangling `original_comm` is still accessible via `PCU::GetMPIComm`. Plus, most users will just be creating a PCU with Split and then `delete`ing or  putting it in a `std::unique_ptr` for automatic deletion. So if we have a sense of ownership and can automatically remove it, then the typical user has less to do. And, they can call `PCU::OwnsComm(false)`, extract the underlying comm with `PCU::GetComm`, and do what they want.

https://github.com/SCOREC/core/blob/437da6845c0d3c7bdc747fa10490ab547f0219a5/parma/group/parma_group.cc#L51-L64

https://docs.open-mpi.org/en/v5.0.1/man-openmpi/man3/MPI_Comm_split.3.html

2025-02-20 16:12 UTC, bobpaw commented
> The other more minor concern is that we should get rid of the need for #ifdefs in the user code by providing our own init and finalize routines. That will substantially clean up the executables.

I was considering adding a specialized `PCU::PCU(int *argc, char ***argv)` which would do MPI_Init and save a flag to run MPI_Finalize later. That specialization would allow users to avoid introducing a scope just for the PCU object because MPI_Finalize will be guaranteed to be called after any pcu_finalize, etc.

Outside of something like that, what is so bad about having #ifdefs? When we discussed, we thought it would help to make it clear what is going on to people looking at tests as examples.

2025-02-20 16:43 UTC, cwsmith commented on pcu/PCU.cc
> +PCU_Comm PCU::GetComm() const noexcept { return mpi_->original_comm; }
I think we should keep it.  Maybe adding a docstring with the suggestion that collective and p2p messaging that involves pumi objects should use PCU interfaces and not direct MPI calls.

2025-02-20 16:51 UTC, cwsmith commented
Are the `#ifdef SCOREC_NO_MPI` macros only used in the examples/drivers?

2025-02-20 22:01 UTC, jacobmerson commented on dsp/CMakeLists.txt
>      )
that makes sense.

2025-02-20 22:09 UTC, bobpaw commented
> Are the `#ifdef SCOREC_NO_MPI` conditionals only used in the examples/drivers?

@cwsmith, the places with `#ifdef SCOREC_NO_MPI` are: tests (including "utils"), some exes in `phasta/`, `pcu/pcu_defines.h`, and `pcu/PCU.h` (for pcu::Time and the default constructor).

2025-02-20 22:12 UTC, jacobmerson commented on pcu/PCU.cc
> +PCU_Comm PCU::SwitchComm(PCU_Comm newcomm) noexcept {
good point.

2025-02-20 22:18 UTC, jacobmerson commented
The thing about ifdefs is it can make the code much more unreadable and the user needs to know under the hood whether they should have MPI or not. If we wrap those ifdefs in our own initialize function then we take care of that subtlety for them.

> I was considering adding a specialized `PCU::PCU(int *argc, char ***argv)` which would do MPI_Init and save a flag to run MPI_Finalize later. That specialization would allow users to avoid introducing a scope just for the PCU object because MPI_Finalize will be guaranteed to be called after any pcu_finalize, etc.

I don't like this solution. The reason we have the PCU object is that we may have many of them lying around with different communicators under the hood, but ultimately still using the same MPI library. I have use cases where this is needed. That constructor means the PCU object may or may not own the MPI initialization. What happens when the owning PCU goes out of scope? All other PCUs that are still alive would break as they would be doing MPI operations after `MPI_finalize`.

So, there needs to be some library/MPI initialization at a higher level than the PCU object.

2025-02-20 22:23 UTC, jacobmerson commented on example/mpi-nompi/hello.cc
> +  pcu::PCU *PCUObj = new pcu::PCU(MPI_COMM_WORLD);
It's not a huge concern here because it's a test driver, but I prefer that we avoid new/delete in all code. Although you know what you are doing there will be grad students who are looking into these files and learning how to code by example. To me the annoyance of an additional scope is better than the bugs we get from leaky code.

2025-02-20 22:25 UTC, jacobmerson commented on pcu/PCU.cc
> +bool PCU::OwnsComm() const noexcept { return mpi_->owned; }
This is my mistake since you marked them in the header file already.

2025-02-21 01:31 UTC, bobpaw commented
> What happens when the owning PCU goes out of scope? All other PCUs that are still alive would break as they would be doing MPI operations after MPI_finalize.

Shouldn't the world-initializing PCU only go out of scope at the end of the main function? Shouldn't all other objects have been destructed by then?

2025-02-21 18:29 UTC, bobpaw commented
I am not touching apfCGNS code yet because pcgnslib.h has `#include "mpi.h"` and therefore CGNS is incompatible with SCOREC_NO_MPI. But I will need to add CMake logic related to the incompatibility and update apfCGNS to not use GetMPIComm.

2025-02-21 18:31 UTC, bobpaw commented
We determined that instead of `PCU::OwnsComm`, we can remove `pcu_mpi_t::original_comm` entirely and also remove `PCU::GetMPIComm` and `PCU::SwitchMPIComm` since those functions only existed because we had to shuffle the MPI_Comm around in the singleton PCU. With the new `pcu::PCU` C++ object, we do not need such functions.

2025-02-24 23:15 UTC, bobpaw commented
SCOREC_NO_MPI is also likely exclusive with ENABLE_ZOLTAN since zoltan.h has `#include <mpi.h>`.

2025-02-25 01:49 UTC, cwsmith commented
> SCOREC_NO_MPI is also likely exclusive with ENABLE_ZOLTAN since zoltan.h has `#include <mpi.h>`.

Hmmm.  Zoltan can be used locally on each process (see the MPI_COMM = SELF) to do what we called 'local part splitting' but that use case then relies on migrating elements to other processes via ... MPI.  So, yes, `ENABLE_ZOLTAN` requires MPI.  Good catch.

2025-02-25 22:53 UTC, bobpaw commented
@cwsmith, I'm running into a subtle bug that I'm hoping you can help with. The test case `pumi3d-1p` is failing intermittently (1/4 or 1/5 of the time) in this new branch. I believe the culprit is a change made in pumi/pumi_mesh.cc, but I cannot figure out how my changes caused this issue. The test is only activated given `ENABLE_ZOLTAN`, and since this code uses `apf::createZoltanSplitter`, it is doing the `MPI_COMM_SELF` splitting like you described. I can additionally share logs of the failing test.

New code:

https://github.com/SCOREC/core/blob/006947468405b1e31a3a22407d10f38fa09c8236/pumi/pumi_mesh.cc#L213-L241

Old code:

https://github.com/SCOREC/core/blob/a900c4761cdc33592be0d5b0c1521cf3996a043d/pumi/pumi_mesh.cc#L234-L260

2025-02-28 11:05 UTC, jacobmerson approved these changes
Looks wonderful! Thankyou for putting this together!

2025-02-28 11:05 UTC, jacobmerson commented on pcu/PCU.h
>  PCU* PCU_GetGlobal();
I know this isn't something you added, but can we remove this? I don't think we store a global PCU pointer anymore.

2025-02-28 15:09 UTC, bobpaw commented on pcu/PCU.h
>  PCU* PCU_GetGlobal();
Sure, it looks like there is no definition anywhere for the C++ or C api version of this call so I will remove it.

2025-02-28 15:22 UTC, bobpaw commented
@cwsmith I have made the changes you and Jacob requested. Can you review when you get the chance?

2025-02-28 16:34 UTC, cwsmith commented
@bobpaw Here is a comment that discusses running the delta wing regression test I mentioned earlier:
https://github.com/SCOREC/core/pull/433#issuecomment-2516069759

2025-02-28 17:29 UTC, bobpaw commented
> @bobpaw Here is a comment that discusses running the delta wing regression test I mentioned earlier: [#433 (comment)](https://github.com/SCOREC/core/pull/433#issuecomment-2516069759)

Do I need to worry about about timing? Or should I just compare the quality file?

2025-02-28 17:30 UTC, cwsmith commented
We should check timing and quality.

2025-03-02 19:15 UTC, bobpaw commented
> We should check timing and quality.

@cwsmith, adapt completed in 5761.497560 seconds. How do I measure the resulting length_proc.txt and quality_proc.txt files? I see there's a histogram utility but it wants min, max, nbins.

2025-03-02 19:19 UTC, cwsmith commented
@bobpaw Hmmm.  I'm guessing that was a serial run?  If so, I only have prior results for a 32 processes (see https://github.com/SCOREC/core/pull/433#issuecomment-2516069759).  Regarding quality, if the final entity counts are similar we should be OK.  We could also render the adapted mesh to sanity check.

2025-03-02 19:19 UTC, bobpaw commented
No, this was a 32proc run on wilbur.

2025-03-02 19:21 UTC, bobpaw commented
But it was a debug build without optimization so let me rerun with release optimizations.

2025-03-02 19:23 UTC, cwsmith commented
For the record, wilbur and piglet have the same hardware.

2025-03-02 19:33 UTC, bobpaw commented
Wow, I'm surprised how much optimizations improved the runtime:

MeshAdapt: mesh adapted in 308.636508 seconds
number of tet 5934317 hex 0 prism 0 pyramid 0
mesh entity counts: v 1067369 e 7026323 f 11893272 r 5934317

2025-03-02 19:36 UTC, cwsmith commented
That time looks good.  Can you please paste your cmake config command and the output log?

2025-03-02 19:46 UTC, bobpaw commented
config/deltaWing.sh:
```sh
#!/bin/sh

build_id=deltaWing
if [ $# -gt 0 ]; then
  build_id=$1
fi

cmake -S . -B build/$build_id \
  -GNinja \
  -DCMAKE_INSTALL_PREFIX="$(realpath install)/$build_id" \
  -DCMAKE_BUILD_TYPE="Release" \
  -DCMAKE_C_COMPILER="mpicc" \
  -DCMAKE_CXX_COMPILER="mpicxx" \
  -DSCOREC_CXX_SYMBOLS=OFF \
  -DSCOREC_CXX_OPTIMIZE=ON \
  -DSCOREC_CXX_WARNINGS=ON \
  -DBUILD_SHARED_LIBS=ON \
  -DBUILD_EXES=ON \
  -DIS_TESTING=ON \
  -DENABLE_ZOLTAN=ON \
  -DENABLE_SIMMETRIX=ON -DSKIP_SIMMETRIX_VERSION_CHECK=ON \
  -DENABLE_FIELDSIM=OFF -DSIM_MPI=mpich4.1.1 -DSIM_ACIS=ON -DSIM_PARASOLID=ON \
  -DPCU_COMPRESS=ON
```

<details>
<summary>
run_adapt.log
</summary>

```
model /lore/smithc11/projects/deltaWingAdapt/pumiAdapt/deltaWing.dmg loaded in 0.000793 seconds
mesh p32/ loaded in 0.062518 seconds
number of tet 581196 hex 0 prism 0 pyramid 0
mesh entity counts: v 104305 e 691152 f 1168044 r 581196
  - verifying tags: mach_ver, original_metric_ver, target_metric_ver
mesh verified in 0.148043 seconds
writeVtuFile into buffers: 0.030325 seconds
writeVtuFile buffers to disk: 0.005144 seconds
vtk files anisoDelta_before written in 0.038241 seconds

MeshAdapt: ma::configure:  Based on requested sizefield, MeshAdapt requires at least 3 iterations.
           Setting the number of iteration to 4!

MeshAdapt: version 2.0 - dev !
planned Zoltan balance to target imbalance 1.100000 in 0.220910 seconds
Zoltan balanced to 1.100000 in 0.524734 seconds

MeshAdapt: iteration 0

MeshAdapt: coarsened 53 edges in 0.272583 seconds

MeshAdapt: refined 611639 edges in 3.049696 seconds

MeshAdapt: --iter 0 of shape correction loop: #bad elements 8683

MeshAdapt: --fixLargeAngles       in 0.430228 seconds: #bad elements 2235

MeshAdapt: --fixShortEdgeElements in 1.284403 seconds: #bad elements 818

MeshAdapt: --percent change in number of bad elements 0.905793

MeshAdapt: --iter 1 of shape correction loop: #bad elements 818

MeshAdapt: --fixLargeAngles       in 0.104712 seconds: #bad elements 288

MeshAdapt: --fixShortEdgeElements in 0.358577 seconds: #bad elements 143

MeshAdapt: --percent change in number of bad elements 0.825183

MeshAdapt: --iter 2 of shape correction loop: #bad elements 143

MeshAdapt: --fixLargeAngles       in 0.043554 seconds: #bad elements 82

MeshAdapt: --fixShortEdgeElements in 0.230717 seconds: #bad elements 58

MeshAdapt: --percent change in number of bad elements 0.594406

MeshAdapt: --iter 3 of shape correction loop: #bad elements 58

MeshAdapt: --fixLargeAngles       in 0.035118 seconds: #bad elements 56

MeshAdapt: --fixShortEdgeElements in 0.198542 seconds: #bad elements 53

MeshAdapt: --percent change in number of bad elements 0.086207

MeshAdapt: --iter 4 of shape correction loop: #bad elements 53

MeshAdapt: --fixLargeAngles       in 0.034678 seconds: #bad elements 52

MeshAdapt: --fixShortEdgeElements in 0.147253 seconds: #bad elements 49

MeshAdapt: --percent change in number of bad elements 0.075472

MeshAdapt: --iter 5 of shape correction loop: #bad elements 49

MeshAdapt: --fixLargeAngles       in 0.032862 seconds: #bad elements 52

MeshAdapt: --fixShortEdgeElements in 0.145992 seconds: #bad elements 49

MeshAdapt: --percent change in number of bad elements 0.000000

MeshAdapt: bad shapes down from 8683 to 49 in 31.149691 seconds

MeshAdapt: iteration 1

MeshAdapt: coarsened 10588 edges in 2.884405 seconds

MeshAdapt: refined 508001 edges in 4.174828 seconds

MeshAdapt: --iter 0 of shape correction loop: #bad elements 21415

MeshAdapt: --fixLargeAngles       in 0.773972 seconds: #bad elements 2934

MeshAdapt: --fixShortEdgeElements in 0.928731 seconds: #bad elements 556

MeshAdapt: --percent change in number of bad elements 0.974037

MeshAdapt: --iter 1 of shape correction loop: #bad elements 556

MeshAdapt: --fixLargeAngles       in 0.114474 seconds: #bad elements 150

MeshAdapt: --fixShortEdgeElements in 0.323925 seconds: #bad elements 71

MeshAdapt: --percent change in number of bad elements 0.872302

MeshAdapt: --iter 2 of shape correction loop: #bad elements 71

MeshAdapt: --fixLargeAngles       in 0.050748 seconds: #bad elements 40

MeshAdapt: --fixShortEdgeElements in 0.133650 seconds: #bad elements 32

MeshAdapt: --percent change in number of bad elements 0.549296

MeshAdapt: --iter 3 of shape correction loop: #bad elements 32

MeshAdapt: --fixLargeAngles       in 0.050780 seconds: #bad elements 28

MeshAdapt: --fixShortEdgeElements in 0.070426 seconds: #bad elements 28

MeshAdapt: --percent change in number of bad elements 0.125000

MeshAdapt: --iter 4 of shape correction loop: #bad elements 28

MeshAdapt: --fixLargeAngles       in 0.049759 seconds: #bad elements 32

MeshAdapt: --fixShortEdgeElements in 0.070114 seconds: #bad elements 28

MeshAdapt: --percent change in number of bad elements 0.000000

MeshAdapt: bad shapes down from 21415 to 28 in 38.095028 seconds

MeshAdapt: iteration 2

MeshAdapt: coarsened 145151 edges in 7.693994 seconds

MeshAdapt: refined 31824 edges in 1.503134 seconds

MeshAdapt: --iter 0 of shape correction loop: #bad elements 1294

MeshAdapt: --fixLargeAngles       in 0.195557 seconds: #bad elements 226

MeshAdapt: --fixShortEdgeElements in 0.222646 seconds: #bad elements 32

MeshAdapt: --percent change in number of bad elements 0.975270

MeshAdapt: --iter 1 of shape correction loop: #bad elements 32

MeshAdapt: --fixLargeAngles       in 0.045653 seconds: #bad elements 17

MeshAdapt: --fixShortEdgeElements in 0.112203 seconds: #bad elements 12

MeshAdapt: --percent change in number of bad elements 0.625000

MeshAdapt: --iter 2 of shape correction loop: #bad elements 12

MeshAdapt: --fixLargeAngles       in 0.045051 seconds: #bad elements 11

MeshAdapt: --fixShortEdgeElements in 0.066190 seconds: #bad elements 11

MeshAdapt: --percent change in number of bad elements 0.083333

MeshAdapt: --iter 3 of shape correction loop: #bad elements 11

MeshAdapt: --fixLargeAngles       in 0.047230 seconds: #bad elements 11

MeshAdapt: --fixShortEdgeElements in 0.057770 seconds: #bad elements 10

MeshAdapt: --percent change in number of bad elements 0.090909

MeshAdapt: --iter 4 of shape correction loop: #bad elements 10

MeshAdapt: --fixLargeAngles       in 0.044678 seconds: #bad elements 10

MeshAdapt: --fixShortEdgeElements in 0.057195 seconds: #bad elements 10

MeshAdapt: --percent change in number of bad elements 0.000000

MeshAdapt: bad shapes down from 1294 to 10 in 31.419985 seconds

MeshAdapt: iteration 3

MeshAdapt: coarsened 29195 edges in 3.057790 seconds

MeshAdapt: refined 4222 edges in 0.570225 seconds

MeshAdapt: --iter 0 of shape correction loop: #bad elements 158

MeshAdapt: --fixLargeAngles       in 0.100734 seconds: #bad elements 56

MeshAdapt: --fixShortEdgeElements in 0.192765 seconds: #bad elements 16

MeshAdapt: --percent change in number of bad elements 0.898734

MeshAdapt: --iter 1 of shape correction loop: #bad elements 16

MeshAdapt: --fixLargeAngles       in 0.044524 seconds: #bad elements 13

MeshAdapt: --fixShortEdgeElements in 0.056625 seconds: #bad elements 11

MeshAdapt: --percent change in number of bad elements 0.312500

MeshAdapt: --iter 2 of shape correction loop: #bad elements 11

MeshAdapt: --fixLargeAngles       in 0.046506 seconds: #bad elements 10

MeshAdapt: --fixShortEdgeElements in 0.056879 seconds: #bad elements 10

MeshAdapt: --percent change in number of bad elements 0.090909

MeshAdapt: --iter 3 of shape correction loop: #bad elements 10

MeshAdapt: --fixLargeAngles       in 0.044946 seconds: #bad elements 10

MeshAdapt: --fixShortEdgeElements in 0.055969 seconds: #bad elements 10

MeshAdapt: --percent change in number of bad elements 0.000000

MeshAdapt: bad shapes down from 158 to 10 in 23.725210 seconds

MeshAdapt: iteration 4

MeshAdapt: coarsened 4361 edges in 1.933079 seconds

MeshAdapt: refined 667 edges in 0.528031 seconds

MeshAdapt: --iter 0 of shape correction loop: #bad elements 55

MeshAdapt: --fixLargeAngles       in 0.099377 second [...]

2025-03-02 20:54 UTC, cwsmith commented
The timing and counts look good.  Here are the final counts from my old run on piglet:

```
MeshAdapt: mesh adapted in 450.370630 seconds
number of tet 5934317 hex 0 prism 0 pyramid 0
mesh entity counts: v 1067369 e 7026323 f 11893272 r 5934317
  - verifying tags: mach_ver, original_metric_ver, target_metric_ver
mesh verified in 1.516892 seconds
```

2025-03-02 23:02 UTC, bobpaw commented
Ok, great! Anything else I need to do before PR is approved?

2025-03-03 15:38 UTC, jacobmerson commented
All set from my end.

2025-03-03 20:31 UTC, cwsmith requested changes
Looks good.  Thank you. I left a couple comments below.

2025-03-03 20:31 UTC, cwsmith commented on pcu/PCU.cc
> +  return MPI_Init(argc, argv);
We should check if MPI was already initialized here (https://www.mpich.org/static/docs/latest/www3/MPI_Initialized.html).  Initializing multiple times is undefined behavior or 'wrong' (https://docs.open-mpi.org/en/v5.0.x/man-openmpi/man3/MPI_Init.3.html#mpi-init, https://www.mpich.org/static/docs/v3.3/www3/MPI_Init.html).

2025-03-03 20:31 UTC, cwsmith commented on pcu/PCU.cc
> +  return MPI_Finalize();
As above, I think we should check if MPI was already finalized before calling finalize ourselves.  https://www.mpich.org/static/docs/latest/www3/MPI_Finalized.html

2025-03-03 21:15 UTC, bobpaw commented on pcu/PCU.cc
> +  return MPI_Init(argc, argv);
Should pcu::PCU_Init throw an exception in this case?

2025-03-03 21:17 UTC, bobpaw commented
Do you think I should rename pcu::PCU_Init to pcu::Init? same suggestion for finalize. The C api I would keep the same. I think it's still namespaced and sorter is nicer.

2025-03-03 21:22 UTC, cwsmith commented on pcu/PCU.cc
> +  return MPI_Init(argc, argv);
Nope, we just don't call initialize.

2025-03-03 21:31 UTC, cwsmith commented
> Do you think I should rename pcu::PCU_Init to pcu::Init? same suggestion for finalize. The C api I would keep the same. I think it's still namespaced and sorter is nicer.

Either way is fine with me.

Another change request: we need to increase the pumi version number to 4.0.0 in CMakeLists.txt as we have changed the api (https://semver.org/).

2025-03-03 21:32 UTC, cwsmith commented on pcu/PCU.cc
> +  return MPI_Init(argc, argv);
That works for me.  Thanks for checking.

2025-03-03 21:34 UTC, bobpaw commented
> > Do you think I should rename pcu::PCU_Init to pcu::Init? same suggestion for finalize. The C api I would keep the same. I think it's still namespaced and sorter is nicer.
> 
> Either way is fine with me.
> 
> Another change request: we need to increase the pumi version number to 4.0.0 in CMakeLists.txt (
> 
> https://github.com/SCOREC/core/blob/17ad033da30c8079a69e8142486ce01892c562b8/CMakeLists.txt#L9
> ) as we have changed the api (https://semver.org/).

Is there anything we want to bundle with this major release?

2025-03-04 01:17 UTC, cwsmith commented
> Is there anything we want to bundle with this major release?

Not that I can think of.

2025-03-04 01:19 UTC, cwsmith commented
/runtests

2025-03-04 01:23 UTC, cwsmith commented
@bobpaw The CI tests caught what I'm guessing is a missing header?

```
 /space/smithc11/githubSelfHostedRunner/actions-runner/_work/core/core/core_425/test/sim_countBL.cc: In function 'int main(int, char**)':
/space/smithc11/githubSelfHostedRunner/actions-runner/_work/core/core/core_425/test/sim_countBL.cc:25:3: error: 'pcu' has not been declared
   25 |   pcu::Init(&argc, &argv);
      |   ^~~
/space/smithc11/githubSelfHostedRunner/actions-runner/_work/core/core/core_425/test/sim_countBL.cc:110:3: error: 'pcu' has not been declared
  110 |   pcu::Finalize();
      |   ^~~
```

2025-03-04 17:14 UTC, bobpaw commented
I think I had to edit that file in the deltaWing example. That file is also using MPI allreduce, peers, etc. so I will need to change a few other lines.

2025-03-04 17:28 UTC, bobpaw commented
/runtests

2025-03-04 17:31 UTC, cwsmith commented
/runtests

2025-03-06 23:47 UTC, cwsmith approved these changes

2025-03-07 01:50 UTC, cwsmith requested changes
Whooops.  I misread the CI test results.  We need to fix the cgns tests.

2025-03-07 02:49 UTC, cwsmith commented
/runtests

2025-03-12 00:44 UTC, cwsmith commented
/runtests

2025-03-12 01:24 UTC, bobpaw commented
@cwsmith would you do the honors?

2025-03-12 01:30 UTC, cwsmith approved these changes

2025-03-12 01:32 UTC, merged